language: node_js

node_js:
  - 8
  - 9
  - 10

before_install:
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest'

before_script:
  - npm install

script:
  - npm run build
  - npm run test
